### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by epage** [tfpk/nominomicon#1]
iirc we've talked before about me forking and adapting this for `winnow`.

I felt I should pass along a post as most of the thanks actually go to you for writing this!

https://github.com/winnow-rs/winnow/discussions/292

**Comment by tfpk** [comment]
Thank you so much for forwarding this, made my day! That said, you've clearly done a heap of work on the tutorial (and I love how you've used the rust docs to make them too! Very cool...), so kudos to you as well :)
